/* eslint-disable sort-keys */
export const languages = {
	de: {
		code: 'de',
		currencyCode: 'EUR',
		currencyIso: 'de-DE',
		dateIso: 'de-DE',
		isDefault: false,
		iso: 'de_DE',
		label: 'Deutschland',
		language: 'de',
		twoLetterShippingCountryCode: 'de',
	},
	at: {
		code: 'at',
		currencyCode: 'EUR',
		currencyIso: 'de-AT',
		dateIso: 'de-DE',
		isDefault: false,
		iso: 'de_AT',
		label: 'Österreich',
		language: 'de',
		twoLetterShippingCountryCode: 'at',
	},
	ch: {
		code: 'ch-de',
		currencyCode: 'CHF',
		currencyIso: 'de-CH',
		dateIso: 'de-CH',
		isDefault: false,
		iso: 'de_CH',
		label: 'Schweiz',
		language: 'de',
		twoLetterShippingCountryCode: 'ch',
	},
	'ch-de': {
		code: 'ch-de',
		currencyCode: 'CHF',
		currencyIso: 'de-CH',
		dateIso: 'de-CH',
		isDefault: false,
		iso: 'de_CH',
		label: 'Schweiz',
		language: 'de',
		twoLetterShippingCountryCode: 'ch',
	},
	uk: {
		code: 'uk',
		currencyCode: 'GBP',
		currencyIso: 'en-GB',
		dateIso: 'en-GB',
		isDefault: false,
		iso: 'en_GB',
		label: 'United Kingdom',
		language: 'en',
		twoLetterShippingCountryCode: 'gb',
	},
	fr: {
		code: 'fr',
		currencyCode: 'EUR',
		currencyIso: 'fr-FR',
		dateIso: 'fr-FR',
		isDefault: false,
		iso: 'fr_FR',
		label: 'France',
		language: 'fr',
		twoLetterShippingCountryCode: 'fr',
	},
	it: {
		code: 'it',
		currencyCode: 'EUR',
		currencyIso: 'it-IT',
		dateIso: 'it-IT',
		isDefault: false,
		iso: 'it_IT',
		label: 'Italia',
		language: 'it',
		twoLetterShippingCountryCode: 'it',
	},
	en: {
		code: 'en',
		currencyCode: 'EUR',
		currencyIso: 'en-EU',
		dateIso: 'en-EU',
		isDefault: true,
		iso: 'en_EU',
		label: 'Rest of Europe',
		language: 'en',
		twoLetterShippingCountryCode: 'de',
	},
}
